clone: 
	git clone https://github.com/lexibank/uralex.git
	git clone https://github.com/lexibank/dunnaslian.git
	git clone https://github.com/lexibank/dravlex.git
	git clone https://github.com/lexibank/felekesemitic.git
	git clone https://github.com/lexibank/wichmannmixezoquean.git
	git clone https://github.com/lexibank/deepadungpalaung.git
	git clone https://github.com/sequencecomparison/hattorijaponic.git
wordlists:
	edictor wordlist -d uralex/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=uralex
	edictor wordlist -d dunnaslian/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=dunnaslian
	edictor wordlist -d dravlex/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=dravlex
	edictor wordlist -d felekesemitic/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=felekesemitic
	edictor wordlist -d deepadungpalaung/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=deepadungpalaung
	edictor wordlist -d hattorijaponic/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=hattorijaponic
	edictor wordlist -d wichmannmixezoquean/cldf/cldf-metadata.json --addon=cogid_cognateset_id:cog --name=wichmannmixezoquean
	echo "finished creating wordlists"

